# Docker Compose for Review Phim Application
services:
  review-phim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: review-phim-app
    restart: unless-stopped
    ports:
      - '3001:3001' # External:Internal port mapping
    environment:
      - NODE_ENV=production
      - PORT=3001
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - YOUTUBE_REGION_CODE=${YOUTUBE_REGION_CODE:-VN}
      - SITE_URL=${SITE_URL}
    env_file:
      - .env
    networks:
      - review-phim-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.review-phim.rule=Host(`reviewphims.com`)'
      - 'traefik.http.routers.review-phim.tls=true'
      - 'traefik.http.routers.review-phim.tls.certresolver=letsencrypt'
      - 'traefik.http.services.review-phim.loadbalancer.server.port=3001'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  review-phim-network:
    driver: bridge
    name: review-phim-net
# Optional: Add Redis for caching (uncomment if needed)
# redis:
#   image: redis:7-alpine
#   container_name: review-phim-redis
#   restart: unless-stopped
#   networks:
#     - review-phim-network
#   command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
